services:
  mariadb:
    image: mariadb:11.8.2
    container_name: mariadb_bdnovaAPI
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_bdnovaAPI
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${DB_ROOT_USER}
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  db_data:
